version: "3.9"

volumes:
    static:

services:
    web:
        build: .
        command: sh migrate_and_run.sh 0.0.0.0:8000
        volumes: 
            - .:/code
            - static:/var/www/data/static
        expose:
            - "8000"
        depends_on:
            - cache
    nginx:
        image: nginx:1.18
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - static:/var/www/data/static
        depends_on:
            - web
    cache:
        image: memcached
        expose:
            - "11211"
        entrypoint:
            - memcached
            - -m 64
