version: "3.9"

services:
    web:
        build: .
        command: sh migrate_and_run.sh 0.0.0.0:8000
        volumes: 
            - .:/code
        ports:
            - "8000:8000"
    cache:
        image: memcached
        ports:
            - "11211:11211"
        entrypoint:
            - memcached
            - -m 64
